name: pravaha Films
favicon: null
layout_spectrum: 0.5662414559628814
typography_spectrum: 0.5009302941616625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  brandStrength: 0.6627375022508204
  lightness: 0.2495954956393689
  saturation: 0.25420795870013535
  rhythmicContrast: 0.22555894730612636
purpose: []
